/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IconLocal:info': typeof import('~icons/local/info')['default']
    'IconMdi:account': typeof import('~icons/mdi/account')['default']
    SelectIcon: typeof import('./src/components/Icon/SelectIcon/index.vue')['default']
    UIcon: typeof import('./src/components/Icon/UIcon/index.vue')['default']
  }
}
